/**
 * @manual.email/db — schema as code (Drizzle / D1).
 *
 * The single source of truth for the relational core: accounts, address
 * resolution, and message metadata. `drizzle-kit generate` derives the SQL
 * migrations in `../migrations` from these definitions, and the inferred
 * `$inferSelect`/`$inferInsert` types below are reused across Workers and
 * the web app.
 *
 * Raw RFC822 bodies + attachments live in R2 — a row points at them via
 * `r2Key` (see `./keys`).
 */

import { sql } from "drizzle-orm";
import {
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

// BetterAuth's core tables live alongside the mail core in the same D1, so
// drizzle-kit (which reads only this file) emits one migration set for both.
export * from "./auth-schema";

const createdAt = () =>
  integer("created_at").notNull().default(sql`(unixepoch() * 1000)`);

/** A platform account (a user / mailbox owner). */
export const accounts = sqliteTable("accounts", {
  createdAt: createdAt(),
  displayName: text("display_name"),
  id: text("id").primaryKey(),
});

/**
 * Account resolution: a fully-qualified, lower-cased address (primary or
 * alias) → the owning account. Inbound routing resolves recipients here.
 */
export const addresses = sqliteTable(
  "addresses",
  {
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    address: text("address").primaryKey(),
    createdAt: createdAt(),
    isPrimary: integer("is_primary", { mode: "boolean" })
      .notNull()
      .default(false),
  },
  (t) => [index("idx_addresses_account").on(t.accountId)],
);

/** Message metadata. The raw bytes live in R2 at `r2Key`. */
export const messages = sqliteTable(
  "messages",
  {
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
    direction: text("direction", {
      enum: ["inbound", "outbound"],
    }).notNull(),
    folder: text("folder", {
      enum: ["inbox", "sent", "archive", "spam", "trash"],
    })
      .notNull()
      .default("inbox"),
    id: text("id").primaryKey(),
    inReplyTo: text("in_reply_to"),
    isRead: integer("is_read", { mode: "boolean" }).notNull().default(false),
    isStarred: integer("is_starred", { mode: "boolean" })
      .notNull()
      .default(false),
    mailFrom: text("mail_from").notNull(),
    messageId: text("message_id"),
    r2Key: text("r2_key").notNull(),
    rcptTo: text("rcpt_to").notNull(),
    receivedAt: integer("received_at").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    subject: text("subject"),
    threadId: text("thread_id"),
  },
  (t) => [
    index("idx_messages_account_received").on(t.accountId, t.receivedAt),
    index("idx_messages_thread").on(t.threadId),
  ],
);

/**
 * Idempotency ledger: keys of inbound messages ingress has fully processed, so
 * queue retries / Email Routing redeliveries are dropped, not reprocessed.
 */
export const processedMessages = sqliteTable("processed_messages", {
  key: text("key").primaryKey(),
  seenAt: integer("seen_at").notNull(),
});

/**
 * Dead-letter store: messages a queue consumer failed to process after its
 * retries were exhausted. Each worker drains its own DLQ into this table so a
 * code-path failure quarantines mail for inspection / replay instead of
 * silently dropping it. `body` is the JSON queue payload.
 */
export const deadLetters = sqliteTable("dead_letters", {
  body: text("body").notNull(),
  failedAt: integer("failed_at").notNull(),
  id: integer("id").primaryKey({ autoIncrement: true }),
  queue: text("queue").notNull(),
});

/**
 * Invite-only signup gate. Codes are friendly three-word strings generated by
 * the db helper; redemption happens in the web auth hook when BetterAuth
 * returns the created user.
 */
export const inviteCodes = sqliteTable(
  "invite_codes",
  {
    code: text("code").primaryKey(),
    createdAt: createdAt(),
    expiresAt: integer("expires_at"),
    reservedAt: integer("reserved_at"),
    usedAt: integer("used_at"),
    usedByUserId: text("used_by_user_id").references(() => user.id, {
      onDelete: "set null",
    }),
  },
  (t) => [
    index("idx_invite_codes_used_by_user").on(t.usedByUserId),
    index("idx_invite_codes_expires").on(t.expiresAt),
  ],
);

/**
 * Filtering organisation. Inbound mail is filtered once at ingest (one Sandbox
 * program invocation per message); the verdict assigns `tags`, and `trays` are
 * saved views over one or more tags.
 */

/** A user label. Many tags per message; `slug` is what filter programs emit,
 *  `label`/`color`/`position` are display metadata the UI owns. */
export const tags = sqliteTable(
  "tags",
  {
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    color: text("color"),
    createdAt: createdAt(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    position: integer("position").notNull().default(0),
    slug: text("slug").notNull(),
  },
  (t) => [uniqueIndex("uniq_tags_account_slug").on(t.accountId, t.slug)],
);

/** Message ↔ tag (the verdict's `tags`). A message can carry many tags. */
export const messageTags = sqliteTable(
  "message_tags",
  {
    messageId: text("message_id")
      .notNull()
      .references(() => messages.id, { onDelete: "cascade" }),
    tagId: text("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (t) => [
    primaryKey({ columns: [t.messageId, t.tagId] }),
    index("idx_message_tags_tag").on(t.tagId),
  ],
);

/**
 * A saved view. `everything` (all passed mail) and `quarantine` (all rejected
 * mail) always exist and aren't tag-backed; `tag` trays show mail carrying any
 * of their `trayTags`.
 */
export const trays = sqliteTable(
  "trays",
  {
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    color: text("color"),
    createdAt: createdAt(),
    icon: text("icon"),
    id: text("id").primaryKey(),
    kind: text("kind", {
      enum: ["everything", "quarantine", "tag"],
    })
      .notNull()
      .default("tag"),
    name: text("name").notNull(),
    position: integer("position").notNull().default(0),
  },
  (t) => [index("idx_trays_account").on(t.accountId)],
);

/** Tray ↔ tag: a `tag` tray is the union of mail carrying any listed tag. */
export const trayTags = sqliteTable(
  "tray_tags",
  {
    tagId: text("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    trayId: text("tray_id")
      .notNull()
      .references(() => trays.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.trayId, t.tagId] })],
);

/**
 * The filtering verdict for an inbound message (1:1). `reject` (or a malformed
 * program output, coerced fail-closed) routes the message to Quarantine;
 * `category`/`reason` are only set for rejects.
 */
export const messageVerdicts = sqliteTable("message_verdicts", {
  category: text("category", { enum: ["spam", "phishing", "other"] }),
  createdAt: createdAt(),
  disposition: text("disposition", { enum: ["pass", "reject"] }).notNull(),
  messageId: text("message_id")
    .primaryKey()
    .references(() => messages.id, { onDelete: "cascade" }),
  reason: text("reason"),
});

/**
 * Per-account filtering configuration. `managed` feeds `safetyPrompt` and
 * `tagPrompt` into the built-in program; `custom` runs the user's
 * `customSource` (`main.ts` default export) — which must pass the system tests
 * before it can be saved.
 */
export const filterConfigs = sqliteTable("filter_configs", {
  accountId: text("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  customSource: text("custom_source"),
  mode: text("mode", { enum: ["managed", "custom"] })
    .notNull()
    .default("managed"),
  safetyPrompt: text("safety_prompt").notNull().default(""),
  tagPrompt: text("tag_prompt").notNull().default(""),
  updatedAt: integer("updated_at").notNull().default(sql`(unixepoch() * 1000)`),
});

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;

export type Address = typeof addresses.$inferSelect;
export type NewAddress = typeof addresses.$inferInsert;

export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;

export type DeadLetter = typeof deadLetters.$inferSelect;
export type NewDeadLetter = typeof deadLetters.$inferInsert;

export type InviteCode = typeof inviteCodes.$inferSelect;
export type NewInviteCode = typeof inviteCodes.$inferInsert;

export type Tag = typeof tags.$inferSelect;
export type NewTag = typeof tags.$inferInsert;

export type MessageTag = typeof messageTags.$inferSelect;
export type NewMessageTag = typeof messageTags.$inferInsert;

export type Tray = typeof trays.$inferSelect;
export type NewTray = typeof trays.$inferInsert;

export type TrayTag = typeof trayTags.$inferSelect;
export type NewTrayTag = typeof trayTags.$inferInsert;

export type MessageVerdict = typeof messageVerdicts.$inferSelect;
export type NewMessageVerdict = typeof messageVerdicts.$inferInsert;

export type FilterConfig = typeof filterConfigs.$inferSelect;
export type NewFilterConfig = typeof filterConfigs.$inferInsert;

/** Kind of saved view a tray represents. */
export type TrayKind = Tray["kind"];

/** Filtering mode an account runs. */
export type FilterMode = FilterConfig["mode"];

/** Direction of a stored message relative to the platform. */
export type MailDirection = Message["direction"];

/** Mailbox folder a message currently lives in. */
export type MailFolder = Message["folder"];
